// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.EvisaEntities
{
    public partial class CountryVisaServices
    {
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string CountryResKey { get; set; }
        public string CssFlag { get; set; }
    }
}