// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.EvisaEntities
{
    public partial class CountryVisaProcesses
    {
        public int Id { get; set; }
        public string OriginCountry { get; set; }
        public string OriginCountryResKey { get; set; }
        public string DestinationCountry { get; set; }
        public string DestinationCountryResKey { get; set; }
        public int CountryVisaTypeFid { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public bool Deleted { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid LastModifiedBy { get; set; }
        public DateTime LastModifiedDate { get; set; }
    }
}