// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.EvisaEntities
{
    public partial class CountryVisaTypes
    {
        public int Id { get; set; }
        public string Country { get; set; }
        public string CountryResKey { get; set; }
        public string VisaTypeName { get; set; }
        public int VisaTypeFid { get; set; }
        public string VisaTypeResKey { get; set; }
        public int NumberOfEntryFid { get; set; }
        public string NumberOfEntryResKey { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public bool Deleted { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid LastModifiedBy { get; set; }
        public DateTime LastModifiedDate { get; set; }
    }
}