// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.EvisaEntities
{
    public partial class VisaApplications
    {
        public long Id { get; set; }
        public string UniqueId { get; set; }
        public string OriginCountry { get; set; }
        public string DestinationCountry { get; set; }
        public string EmailAddress { get; set; }
        public DateTime ArrivalDate { get; set; }
        public DateTime DepartureDate { get; set; }
        public int CountryVisaTypeFid { get; set; }
        public int PortOfArrivalFid { get; set; }
        public string PortOfArrivalName { get; set; }
        public int StatusFid { get; set; }
        public string StatusResKey { get; set; }
        public bool DocumentSubmissionRequired { get; set; }
        public int TotalApplications { get; set; }
        public DateTime SubmissionDate { get; set; }
        public string Remark { get; set; }
        public int VisaProcessOptionFid { get; set; }
        public string CurrencyCode { get; set; }
        public string CultureCode { get; set; }
        public double VisaFee { get; set; }
        public double ProcessingFee { get; set; }
        public double TotalFee { get; set; }
        public bool AlreadyPayment { get; set; }
        public DateTime? PaymentDate { get; set; }
        public bool Deleted { get; set; }
        public Guid? LastModifiedBy { get; set; }
        public DateTime? LastModifiedDate { get; set; }
    }
}