// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.EvisaEntities
{
    public partial class VisaApplicationDocumentDatas
    {
        public long FileId { get; set; }
        public byte[] FileData { get; set; }
    }
}