// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.EvisaEntities
{
    public partial class VisaApplicationDetails
    {
        public long Id { get; set; }
        public long ApplicationFid { get; set; }
        public string FirstAndMiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string GenderResKey { get; set; }
        public string PassportNationalityCode { get; set; }
        public string PassportNationalityName { get; set; }
        public DateTime DayOfBirth { get; set; }
        public string CountryOfBirthCode { get; set; }
        public string CountryOfBirthName { get; set; }
        public string CountryOfResidenceCode { get; set; }
        public string CountryOfResidenceName { get; set; }
        public string PassportNo { get; set; }
        public DateTime? PassportIssuesDate { get; set; }
        public DateTime? PassportExpirationDate { get; set; }
        public DateTime SubmissionDate { get; set; }
        public Guid? LastModifiedBy { get; set; }
        public DateTime? LastModifiedDate { get; set; }
    }
}