// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AQBooking.Admin.Infrastructure.Databases.CMSEntities
{
    public partial class AQCMSContext : DbContext
    {
        public AQCMSContext()
        {
        }

        public AQCMSContext(DbContextOptions<AQCMSContext> options)
            : base(options)
        {
        }

        public virtual DbSet<PostCategories> PostCategories { get; set; }
        public virtual DbSet<PostCategoryDetails> PostCategoryDetails { get; set; }
        public virtual DbSet<PostDetails> PostDetails { get; set; }
        public virtual DbSet<PostFileStreams> PostFileStreams { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Subscribers> Subscribers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PostCategories>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.DefaultName)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.LastModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.ParentFid).HasColumnName("ParentFID");
            });

            modelBuilder.Entity<PostCategoryDetails>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.LanguageFid).HasColumnName("LanguageFID");

                entity.Property(e => e.LastModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.PostCategoryFid).HasColumnName("PostCategoryFID");
            });

            modelBuilder.Entity<PostDetails>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.ActivatedDate).HasColumnType("datetime");

                entity.Property(e => e.FileStreamFid).HasColumnName("FileStreamFID");

                entity.Property(e => e.FileTypeFid).HasColumnName("FileTypeFID");

                entity.Property(e => e.KeyWord).HasMaxLength(255);

                entity.Property(e => e.LanguageFid).HasColumnName("LanguageFID");

                entity.Property(e => e.LastModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.MetaDescription).HasMaxLength(255);

                entity.Property(e => e.PostFid).HasColumnName("PostFId");

                entity.Property(e => e.Title).HasMaxLength(255);

                entity.Property(e => e.UniqueId)
                    .IsRequired()
                    .HasMaxLength(12);
            });

            modelBuilder.Entity<PostFileStreams>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.ActivatedDate).HasColumnType("datetime");

                entity.Property(e => e.FileCategoryFid).HasColumnName("FileCategoryFID");

                entity.Property(e => e.FileCategoryResKey).HasMaxLength(150);

                entity.Property(e => e.FileStreamFid).HasColumnName("FileStreamFID");

                entity.Property(e => e.FileTypeFid).HasColumnName("FileTypeFID");

                entity.Property(e => e.FileTypeResKey).HasMaxLength(150);

                entity.Property(e => e.LastModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.PostFid).HasColumnName("PostFID");
            });

            modelBuilder.Entity<Posts>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.DefaultTitle).HasMaxLength(255);

                entity.Property(e => e.LastModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.PostCategoryFid).HasColumnName("PostCategoryFID");

                entity.Property(e => e.UniqueId)
                    .IsRequired()
                    .HasMaxLength(12);
            });

            modelBuilder.Entity<Subscribers>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.LastModifiedDate).HasColumnType("datetime");

                entity.Property(e => e.ModuleName).HasMaxLength(255);

                entity.Property(e => e.SourceUrl).HasMaxLength(255);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}