// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.CMSEntities
{
    public partial class PostCategoryDetails
    {
        public int Id { get; set; }
        public int PostCategoryFid { get; set; }
        public string Name { get; set; }
        public int LanguageFid { get; set; }
        public bool Deleted { get; set; }
        public bool IsActivated { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? LastModifiedBy { get; set; }
        public DateTime? LastModifiedDate { get; set; }
        public string FriendlyUrl { get; set; }
    }
}