// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.CMSEntities
{
    public partial class PostCategories
    {
        public int Id { get; set; }
        public string DefaultName { get; set; }
        public int? ParentFid { get; set; }
        public double? OrderBy { get; set; }
        public bool IsActivated { get; set; }
        public bool Deleted { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? LastModifiedBy { get; set; }
        public DateTime? LastModifiedDate { get; set; }
    }
}