// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace YachtMerchant.Infrastructure.Database.Entities
{
    public partial class Debugs
    {
        public int Id { get; set; }
        public string Section { get; set; }
        public string LogMessage { get; set; }
        public DateTime LogDate { get; set; }
    }
}