// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.ConfigEntities
{
    public partial class AuthorizationRoles
    {
        public int DesignationId { get; set; }
        public int PageFid { get; set; }
        public int FunctionFid { get; set; }
    }
}