// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.ConfigEntities
{
    public partial class AuthorizationPageFunctions
    {
        public int PageId { get; set; }
        public int FunctionId { get; set; }
    }
}