// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.ConfigEntities
{
    public partial class AuthorizationFunctions
    {
        public int FuntionId { get; set; }
        public string FunctionName { get; set; }
        public string FunctionNameResKey { get; set; }
        public bool? Active { get; set; }
    }
}