// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.ConfigEntities
{
    public partial class Cities
    {
        public int CityCode { get; set; }
        public int CountryCode { get; set; }
        public string CityName { get; set; }
    }
}