// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.ConfigEntities
{
    public partial class CommonLanguages
    {
        public int Id { get; set; }
        public string UniqueId { get; set; }
        public string LanguageName { get; set; }
        public string LanguageCode { get; set; }
        public string CssClass { get; set; }
        public string ResourceKey { get; set; }
        public bool Deleted { get; set; }
        public string Remarks { get; set; }
    }
}