// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.ConfigEntities
{
    public partial class CommonResources
    {
        public string ResourceKey { get; set; }
        public int LanguageFid { get; set; }
        public string ResourceValue { get; set; }
        public string TypeOfResource { get; set; }
    }
}