// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.ConfigEntities
{
    public partial class Countries
    {
        public int CountryCode { get; set; }
        public string CountryName { get; set; }
        public string Description { get; set; }
    }
}