// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.ConfigEntities
{
    public partial class Currencies
    {
        public string CurrencyCode { get; set; }
        public string CultureCode { get; set; }
        public string ResourceKey { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
    }
}