// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace AQBooking.Admin.Infrastructure.Databases.ConfigEntities
{
    public partial class ZoneDistricts
    {
        public int Id { get; set; }
        public int CityCode { get; set; }
        public string ZoneDistrictName { get; set; }
    }
}